name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: './.tool-versions'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy to BunnyCDN
        uses: ayeressian/bunnycdn-storage-deploy@v2.3.0
        env:
          BUNNY_STORAGE: ${{ env.BUNNY_STORAGE }}
          BUNNY_PULL_ZONE_ID: ${{ env.BUNNY_PULL_ZONE_ID }}
        with:
          source: "dist"
          storageZoneName: "klr-io"
          storagePassword: "${{ secrets.BUNNY_API_STORAGE }}"
          accessKey: "${{ secrets.BUNNY_API }}"
          pullZoneId: "3990810"
          upload: "true"
          remove: "true"
          purgePullZone: "true"
